/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP DATABASE IF EXISTS projeto;
CREATE DATABASE IF NOT EXISTS projeto;
USE projeto;

DROP TABLE IF EXISTS NUTS;
DROP TABLE IF EXISTS REGIAO;
DROP TABLE IF EXISTS PROMOTOR;
DROP TABLE IF EXISTS ESPACO;
DROP TABLE IF EXISTS ATIVIDADE;
DROP TABLE IF EXISTS PROMOTOR_ATIVIDADE;
DROP TABLE IF EXISTS ESPACO_ATIVIDADE;

-- tabela NUTS
CREATE TABLE NUTS (
    NUTS_III VARCHAR(255) NOT NULL,
    NUTS_II VARCHAR(255) NOT NULL,
    NUTS_I VARCHAR(255) NOT NULL,
    PRIMARY KEY(NUTS_III)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela REGIAO
CREATE TABLE REGIAO (
    RegiaoId INT NOT NULL AUTO_INCREMENT,
    Distrito VARCHAR(255) NOT NULL,
    NUTS_III VARCHAR(255) NOT NULL,
    PRIMARY KEY (RegiaoID),
    CONSTRAINT regiao_ibfk_1 FOREIGN KEY (NUTS_III) REFERENCES NUTS(NUTS_III) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela PROMOTORES
CREATE TABLE PROMOTOR (
    PromotorId INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Morada VARCHAR(255) NOT NULL,
    CodPostal VARCHAR(127) NOT NULL,
    RegiaoId INT NOT NULL,
    PRIMARY KEY (PromotorId),
    CONSTRAINT promotor_ibfk_1 FOREIGN KEY (RegiaoId) REFERENCES REGIAO(RegiaoId) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela ESPACOS
CREATE TABLE ESPACO (
    EspacoId INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Tipo VARCHAR(255) NOT NULL,
    Lotacao INT NOT NULL,
    Morada VARCHAR(255) NOT NULL,
    RegiaoId INT NOT NULL,
    PRIMARY KEY (EspacoId),
    CONSTRAINT espaco_ibfk_1 FOREIGN KEY (RegiaoId) REFERENCES REGIAO(RegiaoId) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela ATIVIDADES
CREATE TABLE ATIVIDADE (
    AtividadeId INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(255),
    PRIMARY KEY (AtividadeId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela da relacao PRO_ATV
CREATE TABLE PROMOTOR_ATIVIDADE (
    PromotorId INT NOT NULL,
    AtividadeId INT NOT NULL,
    PRIMARY KEY (PromotorId, AtividadeId),
    CONSTRAINT promotor_atividade_ibfk_1 FOREIGN KEY (PromotorId) REFERENCES PROMOTOR(PromotorId) ON UPDATE CASCADE,
    CONSTRAINT promotor_atividade_ibfk_2 FOREIGN KEY (AtividadeId) REFERENCES ATIVIDADE(AtividadeId) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela da relacao ESP_ATV
CREATE TABLE ESPACO_ATIVIDADE (
    EspacoId INT NOT NULL,
    AtividadeId INT NOT NULL,
    PRIMARY KEY (EspacoId, AtividadeId),
    CONSTRAINT espaco_atividade_ibfk_1 FOREIGN KEY (EspacoId) REFERENCES ESPACO(EspacoId) ON UPDATE CASCADE,
	CONSTRAINT espaco_atividade_ibfk_2 FOREIGN KEY (AtividadeId) REFERENCES ATIVIDADE(AtividadeId) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
